import React from "react";
import "./About.css";

import { useEffect } from "react";

const About = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  });
  return (
    <React.Fragment>
      <section className="about pt-16 px-6 mt-10 md:px-20">
        <h1 className="text-4xl md:text-5xl font-semibold text-gray-900 mb-12 text-center md:text-left">
          About Us
        </h1>

        {/* Top Section */}
        <div className="flex flex-col lg:flex-row items-center gap-12 mb-12">
          <div className="flex-1 text-gray-700 text-base md:text-lg leading-relaxed">
            <h3 className="text-2xl font-semibold text-gray-900 mb-4">
              How does TFOR work?
            </h3>
            <p className="space-y-4">
              Our team of experts selects and negotiates the acquisition of
              investment properties. These properties are made up of several
              lots, generally already rented. They allow us to carry out high
              value-added real estate transactions that are usually inaccessible
              to the majority of private individuals.
              <br />
              For each property to be financed, we divide the purchase price by
              $10 to define the supply of the NFT collection associated with the
              properties.
              <br />
              When you collect, you can invest money in the property or
              properties of your choice by purchasing one or more NFTs.
            </p>
          </div>

          {/* Imagem moderna com efeito hover */}
          <div className="flex-1 overflow-hidden rounded-xl shadow-lg">
            <img
              src="https://images.unsplash.com/photo-1721815693498-cc28507c0ba2?q=80&w=1920&auto=format&fit=crop"
              alt="Modern house"
              className="w-full h-auto object-cover transition-transform duration-500 ease-in-out hover:scale-105"
            />
          </div>
        </div>

        <div className="flex flex-col lg:flex-row gap-12 mb-12">
          <div className="flex-1 text-gray-700 text-base md:text-lg leading-relaxed">
            <h3 className="text-2xl font-semibold text-gray-900 mb-4">
              Build your assets with NFT
            </h3>
            <p className="space-y-4">
              Each NFT entitles you to royalties based on the rental income
              generated by the building.
              <br />
              Each month we pay you a fraction of the rent collected, in
              proportion to the number of NFTs you own. This payment is made
              each month to your wallet holding the NFT.
              <br />
              At any time, you can buy or sell more NFTs through the secondary
              market.
            </p>
          </div>

          <div className="flex-1 text-gray-700 text-base md:text-lg leading-relaxed">
            <h3 className="text-2xl font-semibold text-gray-900 mb-4">
              Real estate investment really is accessible to everyone
            </h3>
            <p className="space-y-4">
              Our investment opportunities are accessible to everyone: beginners
              or experienced investors, regardless of income, and regardless of
              your professional situation.
              <br />
              With RoyalCity, you don't need to obtain a mortgage, and you can
              finally invest in real estate without any personal contribution.
              <br />
              Whether you are a student, a young worker, a self-employed person,
              a liberal profession, a company director, an employee or a
              retiree: Welcome to RoyalCity!
            </p>
          </div>
        </div>
      </section>
    </React.Fragment>
  );
};

export default About;
